[package]
name = "capmonster"
version = "0.2.2"
edition = "2024"
repository = "https://github.com/0xlunar/capmonster"
description = "Capmonster.cloud implementation in Rust"
license = "GPL-3.0"

[features]
default = ["reqwest"]
wreq = ["dep:wreq"]
reqwest = ["dep:reqwest"]

[dependencies]
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
tokio = { version = "1.53.1", features = ["time"] }
wreq = { version = "0.16.1", features = ["json"], optional = true }
log = "0.4.34"
reqwest = { version = "0.13.5", features = ["json"], optional = true }

